const machineStatusVariables =
{
  OneTouchDrillCoontrol_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.Border2.TextblockOneTouchDrillControl,
  AirCompressorFilter_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton7,
  AirCompressorFilter_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockAirCompressorFilter,
  EngineAirFilter_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton6,
  EngineAirFilter_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockEngineAirFilter,
  Jack1 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path_896,
  Jack2 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path9,
  Jack3 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path13,
  Jack4 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path22,
  EngineRadiator_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton32,
  EngineRadiator_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockEngineRadiator,
  AirCompressorRadiator_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton25,
  AirCompressorRadiator_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockAirCompressorRadiator,
  RecAirTankPSI_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path10,
  RecAirTankPSI_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockReceiverAirTankPsi,
  AirTemp_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Rectangle3,
  AirTemp_label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockAirTemp,
  EngineRPM_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path11,
  EngineRPM_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockEngineRpm,
  HydraulicPump_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton8,
  HydraulicPump_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockHydraulicPumps,
  OtherOptions_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Button4,
  AirPump1_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path14,
  AirPump1_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelAuxPump1,
  AirPump2FanPump_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path23,
  AirPump2_label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelAuxPump2,
  FanPump_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelFanPump,
  NCSPortB_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path15,
  NCSPortB_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelNcsPortB,
  CSPortB_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path24,
  CSPortB : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelCsPortB,
  Close_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ButtonClose,
  WaterTank_ProgressBar : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ProgressBar,
  WaterTank_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockWaterTank,
  HammerOilTank_ProgressBar : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ProgressBar2,
  HammerOilTank_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockHammerOilTank,
  LubeLevel_ProgressBar : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ProgressBar3,
  LubeLevel_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockLubeLevel,
  HydraulicTank_ProgressBar : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ProgressBar4,
  HydraulicTank_label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockHydraulicTank,
  EngineHours_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockEngineHours,
  HighIdleTime_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockHighIdleTime,
  MediumIdleTime_label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockMediumIdleTime,
  LowIdleTime_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockLowIdleTime,
  DrillingTime_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockDrillingTime,
  Pitch_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockPitch,
  Roll_label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockRoll,
  RadialBubble : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.RadialBubbleLevel2
};

const Sandvik410I_Variables =
{
  EngineRadiator_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockEngineRadiator,
  EngineRadiator_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton32,
  AirCompRadiator_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockAirCompressorRadiator,
  AirCompRadiator_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton25,
  AirCompFilter_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockAirCompressorFilter,
  AirCompFilter_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton7,
  EngineAirFilter_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockEngineAirFilter,
  EngineAirFilter_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton6,
  EngineRPM_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockEngineRpm,
  EngineRPM_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Rectangle4,
  ReceiverAirTankPSI_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockReceiverAirTankPsi,
  ReceiverAirTankPSI_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Ellipse
};

const Sandvik416I_Variables =
{
  CollarTankPressure_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockCollarTankPressure,
  CollarTankPressure_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.HMI_Comp_CollarTankPressure,
  ReceiverTankPressure_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockReceiverTankPressure,
  ReceiverTankPressure_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.HMI_Comp_RcvrTankPress,
  FilterPressNCS_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockFilterPressNcs,
  FilterPressNCS_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.io_Comp_FilterPressNcs,
  FilterPressCS_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockFilterPressCs,
  FilterPressCS_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.io_Comp_FilterPressCs,
  AirTempNCS_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockAirTempNcs,
  AirTempNCS_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.HMI_Comp_AirTempNcs,
  EngineRPM_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockEngineRpm,
  EngineRPM_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path16,
  HYDPump1PSI_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockHydPump1Psi,
  HYDPump2PSI_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockHydPump2Psi,
  HYDPump3PSI_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockHydPump3Psi,
  HYDPump4PSI_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockHydPump4Psi,
  HYDPump5PSI_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockHydPump5Psi
};

const AtlasCopco2714JackWithStairs_Variables =
{
  HydRadiator_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockHydraulicRadiator,
  HydRadiator_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton7,
  EngineRadiator_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockEngineRadiator,
  EngineRadiator_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton6,
  AirCompRadiator_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockAirCompressorRadiator,
  AirCompRadiator_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton25,
  AirTemp_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockAirTemp,
  AirComp_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockAirCompressor,
  AirTempAirComp_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton32,
  ReceiverAirTankPSI_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockReceiverAirTankPsi,
  ReceiverAirTankPSI_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Rectangle22,
  EngineRPM_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockEngineRpm,
  EngineRPM_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path32,
  HydReturnFilter_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockHydraulicReturnFilters,
  HydReturnFilter_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path42,
  HydTank_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockHydraulicTank2,
  HydTank_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path52,
  HydDrainFilter_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockHydraulicDrainFilters,
  HydDrainFilter_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton26,
  LubeLevel_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockLubeLevel2,
  LubeLevel_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Rectangle32,
  HydPump_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockHydraulicPumps2,
  HydPump_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton8,
  OtherOption_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Button4,
  NCSPortA_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelNcsPortA,
  NCSPortB_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelNcsPortB2,
  CSPortA_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelCsPortA,
  CSPortB_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelCsPortB2,
  OtherOptClose_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ButtonClose2
};

const AtlasCopco271MastStairs_Variables =
{
  HydRadiator_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockHydraulicRadiator,
  HydRadiator_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton7,
  EngineRadiator_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockEngineRadiator,
  EngineRadiator_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton6,
  AirCompRadiator_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockAirCompressorRadiator,
  AirCompRadiator_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton25,
  AirTemp_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockAirTemp,
  AirComp_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockAirCompressor,
  AirTempAirComp_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton32,
  ReceiverAirTankPSI_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockReceiverAirTankPsi,
  ReceiverAirTankPSI_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Rectangle22,
  EngineRPM_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockEngineRpm,
  EngineRPM_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path32,
  HydReturnFilter_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockHydraulicReturnFilters,
  HydReturnFilter_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path42,
  HydTank_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockHydraulicTank2,
  HydTank_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path52,
  HydDrainFilter_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockHydraulicDrainFilters,
  HydDrainFilter_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton26,
  LubeLevel_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockLubeLevel2,
  LubeLevel_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Rectangle32,
  HydPump_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockHydraulicPumps2,
  HydPump_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton8,
  OtherOption_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Button4,
  NCSPortA_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelNcsPortA,
  NCSPortB_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelNcsPortB2,
  CSPortA_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelCsPortA,
  CSPortB_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelCsPortB2,
  OtherOptClose_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ButtonClose2
};

const Epiroc271E_Variables =
{
  HydRadiator_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockHydraulicRadiator,
  HydRadiator_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton7,
  AirCompRadiator_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockAirCompressorRadiator,
  AirCompRadiator_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton6,
  AirTemp_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockAirTemp,
  AirComp_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockAirCompressor,
  AirTempAirComp_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton25,
  ReceiverAirTankPSI_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockReceiverAirTankPsi,
  ReceiverAirTankPSI_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Rectangle42,
  MotorRPM_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockMotorRpm,
  MotorRPM_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path17,
  HydPump_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockHydraulicPumps2,
  HydPump_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton32,
  HydReturnFilter_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockHydraulicReturnFilters,
  HydReturnFilter_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton33,
  HydTank_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockHydraulicTank2,
  HydTank_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path32,
  HydDrainFilter_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockHydraulicDrainFilters,
  HydDrainFilter_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ToggleButton42,
  LubeLevel_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockLubeLevel2,
  LubeLevel_UI : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Rectangle5
};

module.exports = {machineStatusVariables, Sandvik410I_Variables, Sandvik416I_Variables, AtlasCopco2714JackWithStairs_Variables, AtlasCopco271MastStairs_Variables,
Epiroc271E_Variables};