const maint_HeadLimit_Variables =
{
  HeadLimit_Gauge : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LinearGaugeHeadPosition,
  HeadPosition_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelHeadPosition,
  HeadUpperLimit_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelHeadUpperLimit,
  UpperSlowDownRange_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelUpperSlowDownRange,
  PipeRackLimit_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelPipeRackLimit,
  HeadMastControlUpper_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelHeadMastControlUpper,
  HeadMastControlLower_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelHeadMastControlLower,
  AutoDrillStopSetpoint_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelAutoDrillStopSetpoint,
  PropelLimit_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelPropelLimit,
  PropelDrop_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelPropelDrop,
  RodSupportStow_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelRodSupportStow,
  RodSupportAlarm_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelRodSupportAlarm,
  RodSupportFault_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelRodSupportFault,
  Lower_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelLower,
  BorderBox_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border,
  HeadPositionYellow_Bar : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border.Border,
  HeadPositionGreen_Bar : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border.Border2,
  HeadPositionBlue_Bar : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border.Border3,
  HeadPositionRed_Bar : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border.Border4,
  HeadPositionViolet_Bar : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border.Border5,
  EnterMaintMode_btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ButtonEnterMaintenanceMode2,
  ExitMaintMode_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ButtonExitMaintenanceMode2,
  SetupHoistResolver_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ButtonSetupHoistResolver,
  SetupHoistResolverPanel : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17,
  SetupHoistResolverPanel_Title : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelHeadResolverSetup,
  SetupResolverCard_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ButtonSetupResolverCard,
  ResetHoistPosition_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ButtonResetHoistPosition,
  SetCountPer_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ButtonSetCountPerFoot,
  HoistResolverPanelOK_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ButtonOk,
  HoistResolverPanelClose_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.Button3,
  HoistResolverPanelBack_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.Button8,
  ConfirmationPopUpSetupResolverCard : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MessageQuestion2.MessageQuestion.MessageText,
  ConfirmationPopUpSetupResolverCardYes_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MessageQuestion2.MessageQuestion.YesButton,
  ConfirmationPopUpResetHoistPos : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MessageQuestion3.MessageQuestion.MessageText,
  ConfirmationPopUpResetHoistPosYes_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MessageQuestion3.MessageQuestion.YesButton
};

const maint_Consumable_Variable =
{
  Change_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ScrollView.TextblockChange,
  BitOption_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ScrollView.TextblockBit,
  Stabilizer_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ScrollView.TextblockStabilizer,
  LowerSteel_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ScrollView.TextblockLowerSteel,
  UpperSteel_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ScrollView.TextblockUpperSteel,
  ThreadSaver_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ScrollView.TextblockThreadSaver,
  EnterMaintMode_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ScrollView.Button,
  ExitMaintMode_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ScrollView.Button2,
  ExitMaintMode_Btn_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ScrollView.TextblockExitMaintenanceMode
}

const maint_MaintTest_Variable =
{
  IOStatus_Btn_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockIOStatus,
  IOStatus_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ButtonIOStatus,
  KeypadStatus_Btn_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TextblockKeypadStatus,
  KeypadStatus_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ButtonKeypadStatus,
  JoystickStatus_Btn_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ButtonJoystickStatus.TextblockJoystickStatus,
  JoystickStatus_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ButtonJoystickStatus,
  Status_TabControl : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl,
  Device_IOModule : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.Border,
  Keypad_Module : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.Path,
  Back_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.MoveBack
}

const maint_Interlock_Variable =
{
  SystemInterlockStatus_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ItemsControl.ButtonRepeater.ButtonSystemInterlockStatus,
  FeedInterlockStatus_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ItemsControl.ButtonFeedInterlockStatus,
  RotaryInterlockStatus_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ItemsControl.ButtonRepeater.ButtonRotaryInterlockStatus,
  PropelInterlockStatus_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ItemsControl.ButtonPropelInterlockStatus,
  RemotePropelInterlockStatus_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ItemsControl.ButtonRepeater2.ButtonRemotePropelInterlockStatus,
  AutoPropelInterlockStatus_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ItemsControl.ButtonRepeater2.ButtonAutoPropelInterlockStatus,
  AutoDrillInterlockStatus_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ItemsControl.ButtonAutoDrillInterlockStatus,
  MastInterlockStatus_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ItemsControl.ButtonMastInterlockStatus,
  JackSystemInterlockStatus_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ItemsControl.ButtonJackSystemInterlockStatus,
  ScreenDiagram : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.myDiagram,
  Back_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.btnBack,
  DialogueBox : Aliases.Flanders_Ardvarc_Hmi_Client.dlg,
  DialogueOK_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.dlg.btnOK
}

const maint_JoystickStatus_Variable =
{
  MarkIV_LH_PB1 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.MainBorder.Path72,
  MarkIV_RH_PB1 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path,
  MarkIV_LH_WaterInjectionOnOff_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.MainBorder.LabelWaterInjectionOnOff,
  MarkIV_RH_DrillControlOnOff_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelDrillControlOnOff,
  MarkIV_LH_PB2 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.MainBorder.Path,
  MarkIV_RH_PB2 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path2,
  MarkIV_LH_FeedOverrideOnOff_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.MainBorder.LabelFeedOverrideOnOff,
  MarkIV_RH_ThreadLubeOn_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelThreadLubeOn,
  MarkIV_LH_PB3 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.MainBorder.Path2,
  MarkIV_RH_PB3 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path3,
  MarkIV_LH_OneTouchDrillOnOff_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.MainBorder.LabelOneTouchDrillOnOff,
  MarkIV_RH_WorkingAirOnOff_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelWorkingAirOnOff,
  MarkIV_LH_PB4 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.MainBorder.Path22,
  MarkIV_RH_PB4 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path4,
  MarkIV_LH_DeckWrenchOut_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.MainBorder.LabelDeckWrenchOut,
  MarkIV_RH_PipeSupportIn_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelPipeSupportIn,
  MarkIV_LH_PB5 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.MainBorder.Path3,
  MarkIV_RH_PB5 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path5,
  MarkIV_LH_DeckWrenchIn_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.MainBorder.LabelDeckWrenchIn,
  MarkIV_RH_PipeSupportOut_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelPipeSupportOut,
  MarkIv_LH_Wheel1 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.MainBorder.Path4,
  MarkIv_RH_Wheel1 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path6,
  MarkIV_LH_LeftWheel1_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.MainBorder.LabelLeftwheel1text,
  MarkIV_RH_RightWheel1_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelRightwheel1text,
  MarkIV_LH_LinearGaugeLeftWheel1 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.MainBorder.LinearGaugeLeftWheel1,
  MarkIV_RH_LinearGaugeRightWheel1 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LinearGaugeRightWheel1,
  MarkIv_LH_Wheel2 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.MainBorder.Path5,
  MarkIv_RH_Wheel2 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path7,
  MarkIV_LH_LeftWheel2_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.MainBorder.LabelLeftwheel2text,
  MarkIV_RH_RightWheel2_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelRightwheel2text,
  MarkIV_LH_LinearGaugeLeftWheel2 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.MainBorder.LinearGaugeLeftWheel2,
  MarkIV_RH_LinearGaugeRightWheel2 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LinearGaugeRightWheel2,
  MarkIV_RH_PB6 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Ellipse,
  MarkIv_LH_Wheel3 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.MainBorder.Path23,
  MarkIv_RH_Wheel3 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path8,
  MarkIV_LH_LeftWheel3_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.MainBorder.LabelLeftwheel3text,
  MarkIV_RH_RightWheel3_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelRightwheel3text,
  MarkIV_LH_PB6AndLinearGaugeLeftWheel3 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.MainBorder.LinearGaugeLeftWheel3,
  MarkIV_RH_PB6AndLinearGaugeRightWheel3 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LinearGaugeRightWheel3,
  MarkIV_LH_Deadman_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.MainBorder.LabelDeadman,
  MarkIV_RH_Deadman_Label : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelDeadman,
  MarkIV_LH_Deadman : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.MainBorder.Rectangle,
  MarkIV_RH_Deadman : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Rectangle,
  MarkIV_LH_Deadman_Label2 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.MainBorder.LabelDeadman2,
  MarkIV_RH_Deadman_Label2 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LabelDeadman2,
  MarkIV_LH_WholeHandle : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.MainBorder.Path6,
  MarkIV_RH_WholeHandle : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Path82,
  MarkIV_LH_LinearGauge : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LinearGaugeLeft,
  MarkIV_RH_LinearGauge : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.LinearGaugeRight,
  Value_Borders : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.MainBorder,
  Other_Value_Option : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow,
}

const maint_Fluid_Variable =
{
  Fluid_Panel : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17,
  FluidPanel_Title : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.TextblockFluidInput,
  FluidSelectDropdown_Title : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.TextblockSelectFluidType,
  EnterAmountDropdown_Title : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.TextblockEnterTheAmountOfFluidAdded,
  SelectFluidTypeDropdown : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.ComboBox,
  LiterLabel : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.LabelLitres,
  DropdownOptions : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_PopupRoot.PopupRoot.NonLogicalAdornerDecorator,
  Calculator_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.Button,
  CaluclatorWindow : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_CalculatorWindow.CalculatorWindow,
  MsgText : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MessageWithOk.MessageWithOk.MessageText,
  MsgOK_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MessageWithOk.MessageWithOk.OkButton,
  Cancel_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.ButtonCancel,
  Save_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.ButtonSave,
  Error_Msg : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MessageWithOk2.MessageWithOk.MessageText,
  ErrorMsgOk_Btn : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MessageWithOk2.MessageWithOk.OkButton,
  SavedTick : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.Border.LabelSaved
}

const maint_EngineLog_Variable =
{
  EngineLogTable : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.Border2.ErrorDataGrid,
  LampColumn_Title : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.Border2.ErrorDataGrid.DatagridcolumnheaderLamp,
  WhenColumn_Title : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.Border2.ErrorDataGrid.DatagridcolumnheaderWhen,
  CodeColumn_Title : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.Border2.ErrorDataGrid.DatagridcolumnheaderCode,
  FMIColumn_Title : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.Border2.ErrorDataGrid.DatagridcolumnheaderFmi,
  SPNColumn_Title : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.Border2.ErrorDataGrid.DatagridcolumnheaderSpn,
  DescriptionColumn_Title : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.Border2.ErrorDataGrid.DatagridcolumnheaderDescription,
  ErrorWCIColumn_Title : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.Border2.ErrorDataGrid.DatagridcolumnheaderErrorwci,
  EIDCIDColumn_Title : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.Border2.ErrorDataGrid.DatagridcolumnheaderEidCid,
  EngineLogTable_DataGrid : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.Border2.ErrorDataGrid,
  SingleLineMove_Down_Arrow : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.Button6,
  SingleLineMove_Up_Arrow : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.Button5,
  NextPageLineMove_Down_Arrow : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.Button2,
  PreviousPageLineMove_Up_Arrow : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.Button3,
  LastLine_Down_Arrow : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.Button4,
  FirstLine_Up_Arrow : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Border17.Button7,
  FirstRow_EngineLogTable : NameMapping.Sys.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.Grid3.Border.Border2.ErrorDataGrid.DataGridRow32
}

const maint_MachineMonitor_Variable =
{
  LubeTab : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.TabitemLube,
  MainMotorTab : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.TabitemMainMotor,
  MastTab : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.TabitemMast,
  MiscellaneousTab : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.TabitemMiscellaneous,
  PipeRackTab : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.TabitemPipeRack,
  PowerTab : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.TabitemPower,
  PropelTab : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.TabitemPropel,
  RotaryTab : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.TabitemRotary,
  StairsTab : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.TabitemStairs,
  WaterInjectionTab : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.TabitemWaterInjection,
  WinchTab : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.TabitemWinch,
  WiperWasherTab : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.TabitemWipersWashers,
  BreakOutTab : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.TabitemBreakOut,
  CableReelTab : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.TabitemCableReel,
  CompressorTab : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.TabitemCompressor,
  DeckForkTab : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.TabitemDeckFork,
  DeckHatchTab : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.TabitemDeckHatch,
  DustCurtainTab : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.TabitemDustCurtain,
  EStopsTab : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.TabitemEStops,
  FlandersIOTab : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.TabitemFlandersIo,
  HoistTab : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.TabitemHoist,
  HydraulicTab : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.TabitemHydraulic,
  LevelingTab : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.TabitemLeveling,
  LightsTab : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.TabitemLights,
  Data : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.ScrollViewer,
  Data1 : Aliases.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.TabControl.ScrollViewer2,
  DataInTab : NameMapping.Sys.Flanders_Ardvarc_Hmi_Client.HwndSource_MainWindow.MainWindow.ItemsControl
}

module.exports = {maint_HeadLimit_Variables, maint_Consumable_Variable, maint_MaintTest_Variable, 
maint_Interlock_Variable, maint_JoystickStatus_Variable, maint_Fluid_Variable, 
maint_EngineLog_Variable, maint_MachineMonitor_Variable};